# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 239)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.startStreamImmediately = QtWidgets.QCheckBox(self.centralwidget)
        self.startStreamImmediately.setWhatsThis("")
        self.startStreamImmediately.setChecked(True)
        self.startStreamImmediately.setObjectName("startStreamImmediately")
        self.gridLayout_3.addWidget(self.startStreamImmediately, 3, 2, 1, 1)
        self.appOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.appOutput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.appOutput.setReadOnly(True)
        self.appOutput.setCenterOnScroll(True)
        self.appOutput.setPlaceholderText("")
        self.appOutput.setObjectName("appOutput")
        self.gridLayout_3.addWidget(self.appOutput, 7, 0, 1, 3)
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setInputMask("")
        self.lineName.setMaxLength(30)
        self.lineName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineName.setObjectName("lineName")
        self.gridLayout_3.addWidget(self.lineName, 1, 1, 1, 2)
        self.labelServerIP = QtWidgets.QLabel(self.centralwidget)
        self.labelServerIP.setObjectName("labelServerIP")
        self.gridLayout_3.addWidget(self.labelServerIP, 0, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setObjectName("labelName")
        self.gridLayout_3.addWidget(self.labelName, 1, 0, 1, 1)
        self.labelPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout_3.addWidget(self.labelPassword, 2, 0, 1, 1)
        self.labelStreamImmediately = QtWidgets.QLabel(self.centralwidget)
        self.labelStreamImmediately.setObjectName("labelStreamImmediately")
        self.gridLayout_3.addWidget(self.labelStreamImmediately, 3, 0, 1, 2)
        self.lineServerIP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineServerIP.setAutoFillBackground(False)
        self.lineServerIP.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineServerIP.setMaxLength(15)
        self.lineServerIP.setFrame(True)
        self.lineServerIP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineServerIP.setReadOnly(False)
        self.lineServerIP.setPlaceholderText("")
        self.lineServerIP.setObjectName("lineServerIP")
        self.gridLayout_3.addWidget(self.lineServerIP, 0, 1, 1, 2)
        self.linePassword = QtWidgets.QLineEdit(self.centralwidget)
        self.linePassword.setMaxLength(30)
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePassword.setAlignment(QtCore.Qt.AlignCenter)
        self.linePassword.setObjectName("linePassword")
        self.gridLayout_3.addWidget(self.linePassword, 2, 1, 1, 2)
        self.disconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectButton.setObjectName("disconnectButton")
        self.gridLayout_3.addWidget(self.disconnectButton, 6, 0, 1, 3)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_3.addWidget(self.connectButton, 5, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CameraAPP"))
        self.startStreamImmediately.setText(_translate("MainWindow", "YES"))
        self.labelServerIP.setText(_translate("MainWindow", "Server IP:"))
        self.labelName.setText(_translate("MainWindow", "Name:"))
        self.labelPassword.setText(_translate("MainWindow", "Password:"))
        self.labelStreamImmediately.setText(_translate("MainWindow", "Do you want to start streaming immediately?"))
        self.lineServerIP.setInputMask(_translate("MainWindow", "000.000.000.000"))
        self.lineServerIP.setText(_translate("MainWindow", "..."))
        self.disconnectButton.setText(_translate("MainWindow", "STOP STREAMING"))
        self.connectButton.setText(_translate("MainWindow", "START STREAMING"))




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
